hardware:
  encoders:
    - id: 1
      midi_CC: 104
      midi_port: Source Audio C4 Synth
      longpress: previous_snapshot
    - id: 2
      midi_CC: 71
      longpress: next_snapshot
    - id: 3
      type: VOLUME
  external_midi:
    enabled: true
